[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name="github.com/rs/zerolog"
  version="v1.8.0"

[[constraint]]
  name="github.com/spf13/cobra"
  version="v0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.3.2"

[[constraint]]
  name = "github.com/nalej/derrors"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/nalej/grpc-edge-controller-go"
  version = "v0.0.5"

[[constraint]]
  name = "github.com/nalej/grpc-inventory-manager-go"
  version = "v0.0.7"

[[constraint]]
  name = "github.com/nalej/grpc-inventory-go"
  version = "v0.0.4"

[[constraint]]
  name = "github.com/nalej/grpc-utils"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/nalej/sysinfo"
  #version = "v1.0.0"
  branch = "feature/NP-1258_Add_fake_sysinfo_for_tests"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.20.1"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v19"

[[constraint]]
  name = "github.com/denisbrodbeck/machineid"
  version = "v1.0.1"
